model:
    client_devices:
        client1:
            mac_addr: 01:01:01:01:01:01
            client_type: phone
            traffic_type: interactive
        client2:
            mac_addr: 02:02:02:02:02:02
            client_type: phone
            traffic_type: telephony
        client3:
            mac_addr: 03:03:03:03:03:03
            client_type: phone
            traffic_type: telephony
        client4:
            mac_addr: 04:04:04:04:04:04
            client_type: phone
            traffic_type: download
        client5:
            mac_addr: 05:05:05:05:05:05
            client_type: phone
            traffic_type: download
    access_points:
        AP148:
            type: CAP
            mac_addr: "11:11:11:00:00:01"
            vaps:
                2.4g:
                    iface_name: ath1
                    radio_iface: wifi1
                    band: 2.4
                    channel: 1
                    channel_group: 24G
                    overload_threshold: 70
                5g:
                    iface_name: ath0
                    radio_iface: wifi0
                    band: 5
                    channel: 149
                    channel_group: 5GH
                    overload_threshold: 70
view:
    type: graphical
controller:
    ap_consoles:
        AP148:
            type: telnet
            hostname: 192.168.1.1
            shell_prompt: /#
